### ISSUE TITLE
Pandas FutureWarning: frame.append deprecated, use pandas.concat instead

### ISSUE THREAD

**Issue by mslw** [datalad/datalad-neuroimaging#102]
This message is from the test run with Pandas 1.4.0 on Python 3.9:
```FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.```

This has been deprecated [in Pandas 1.4.0](https://pandas.pydata.org/pandas-docs/stable/whatsnew/v1.4.0.html#deprecated-dataframe-append-and-series-append) less than a month ago, so there's no urgency.

FWIW, `git grep` shows 49 occurrences of "append" and it looks like few of them are dataframe operations.

**Comment by jsheunis** [comment]
Created an issue in pybids here: https://github.com/bids-standard/pybids/issues/830

**Comment by mslw** [comment]
Pybids issue is long resolved, and when running tests on a fresh install with Python 3.9, pandas-1.5.3, and pybids-0.15.5 this particular warning is gone.
