### ISSUE TITLE
Crippled file system test failure

### ISSUE THREAD

**Issue by jsheunis** [datalad/datalad-neuroimaging#106]
This was the last time it ran successfully: https://github.com/datalad/datalad-neuroimaging/actions/runs/2320161731

**Comment by jsheunis** [comment]
Seems like the issue was introduced with datalad 0.17.0. Relevant issue here: https://github.com/datalad/datalad/issues/7000. Interim solution: downgrade datalad version to <0.17 until fix is released for datalad.

**Comment by mslw** [comment]
- Several recent crippled file system builds passed, including the most recent one with datalad-0.18.1.
- Dependency pinning has been lifted in efbc9ee (`setup.cfg` currently states  `datalad >= 0.16.7`)
- PR fixing the related DataLad issue has been released in `0.17.7`

I think this can be safely closing (although I wonder whether that would justify bumping DataLad requirement - but I think a closed issue still carries the information).
