### ISSUE TITLE
Automate releasing process

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-neuroimaging#127]
We have now since https://github.com/datalad/datalad-extension-template/pull/49 -- out release action automation. But this poor package haven't seen releases for a year although some fixes were introduced.  We need to bring in automation and cut a release.

**Comment by yarikoptic** [comment]
Please prepare PR etc to automate using datalad's release action @jwodder

**Comment by yarikoptic-gitmate** [comment]
Issue fixed in [`0.3.5`](https://github.com/datalad/datalad-neuroimaging/releases/tag/0.3.5)
