### ISSUE TITLE
BIDS extractor outdated

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad-neuroimaging#38]
Changes in `pybids` (see https://github.com/INCF/pybids/commit/025341a156634ec43457b0f2e174e1b1a7802493) lead to tests currently failing with sth like:

```
datalad.metadata.metadata: INFO: Engage bids metadata extractor
datalad.metadata.metadata: ERROR  : Failed to get dataset metadata (bids): __init__() got an unexpected keyword argument 'config' [bids_layout.py:__init__:116]
```

`extractors/bids.py` needs adaption on how to instantiate `BIDSLayout`.

**Comment by mih** [comment]
Current master is compatible with 0.6.4 again. Needs reinstall to loose that error.
