### ISSUE TITLE
Build neuroimaging-enabled singularity image

### ISSUE THREAD

**Issue by mih** [datalad/datalad-neuroimaging#4]

**Comment by mih** [comment]
Done: https://singularity-hub.org/collections/841

**Comment by yarikoptic** [comment]
I really see no point of breeding singularity images for datalad for each domain of endeavor, and do not see why there could be no `datalad-complete` or alike which would provide full installation of datalad with all "approved" extensions.

**Comment by mih** [comment]
I need this particular image myself, there is no other one that I can use, nor do I want one with any additional (hypothetical) extensions for this purpose. Where is the problem?

**Comment by yarikoptic** [comment]
Why not to create `datalad-complete` which would install all extensions? or why `datalad/datalad` (https://singularity-hub.org/collections/667) cannot fulfill that role (as it did before if I got it right)
