### ISSUE TITLE
get_bids_dataset is broken

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad-neuroimaging#57]
Ran into it via datalad-hirni's Travis setup (see https://github.com/psychoinformatics-de/datalad-hirni/issues/93).

On a fresh system (no cached bversions of the test datasets, that are submodules of datalad-neuroimaging):

```python

from datalad_neuroimaging.tests.utils import get_bids_dataset  

ds = get_bids_dataset()

<snip>


[INFO   ] == Command exit (modification check follows) ===== 
INFO   : == Command exit (modification check follows) =====
[ERROR  ] dataset containing given paths is not underneath the reference dataset <Dataset path=/home/ben/.cache/datalad/datalad_neuroimaging_srcrepo/datalad_neuroimaging/tests/data/bids>: [PosixPath('/home/ben/.cache/datalad/datalad_neuroimaging_srcrepo/datalad_neuroimaging/tests/data/bids')] [status(/home/ben/.cache/datalad/datalad_neuroimaging_srcrepo)] 
ERROR  : dataset containing given paths is not underneath the reference dataset <Dataset path=/home/ben/.cache/datalad/datalad_neuroimaging_srcrepo/datalad_neuroimaging/tests/data/bids>: [PosixPath('/home/ben/.cache/datalad/datalad_neuroimaging_srcrepo/datalad_neuroimaging/tests/data/bids')] [status(/home/ben/.cache/datalad/datalad_neuroimaging_srcrepo)]
---------------------------------------------------------------------------
IncompleteResultsError                    Traceback (most recent call last)
<ipython-input-3-7f9e1a26998f> in <module>
----> 1 ds = get_bids_dataset()

<snip>

```

This is the same that can be found here: https://travis-ci.org/psychoinformatics-de/datalad-hirni/jobs/518791608

**Comment by bpoldrack** [comment]
FTR: This is happening during modification save of a  `run` call to heudiconv.

**Comment by bpoldrack** [comment]
Hm. That `status` gets called by `core/local/save` at line 189. `dataset` argument is the bids dataset `/home/ben/.cache/datalad/datalad_neuroimaging_srcrepo/datalad_neuroimaging/tests/data/bids` (correct, since this is supposed to be thing the conversion is running on) and the `path` argument to status is `.`. Apparently this is resolved to the superproject's root, leading to the error.
Not sure yet, where exactly this dot is resolved and why it resolves to the wrong thing.
However, seems increasingly like an issue in datalad core.

@mih: Any thoughts on that?

**Comment by kyleam** [comment]
@bpoldrack
> Hm. That `status` gets called by `core/local/save` at line 189. `dataset` argument is the bids dataset `/home/ben/.cache/datalad/datalad_neuroimaging_srcrepo/datalad_neuroimaging/tests/data/bids` (correct, since this is supposed to be thing the conversion is running on) and the `path` argument to status is `.`. Apparently this is resolved to the superproject's root, leading to the error.
> Not sure yet, where exactly this dot is resolved and why it resolves to the wrong thing.
> However, seems increasingly like an issue in datalad core.

Sounds like something recently addressed in core.  Do you still see this
issue after core's 3dea65a9b (BF: status: Provide special treatment of
"." path, 2019-04-12)?

**Comment by bpoldrack** [comment]
@kyleam : Missed that one indeed (missed a lot while moving) and it does look like it is the issue. Works locally. If datalad-hirni passes on Travis, I'll close. Thanks!

**Comment by bpoldrack** [comment]
Ok. Solved in datalad-core. Thanks @kyleam .
