### ISSUE TITLE
AFNI dereferences files while accessing them

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-neuroimaging#84]
thus being uncapable to open .BRIKs since .HEADs would be in another key directory:

```
$> afni 0back_SD_tbi-hc+tlrc.BRIK  

Thanks go to J Haxby for much encouragement

Initializing: X11.. Widgets...... Input files:ONLY ATLASES
** Couldn't open .../.git/annex/objects/fW/24/SHA256E-s2280000--b3b0....BRIK as session OR as dataset!

```

Workaround -- use `AFNI_NOREALPATH=yes`.  I guess we might need to research either this could be a better default and then campaign for it!

**Comment by yarikoptic** [comment]
Uff.. I have no split personality, and there is no evil ghosts. I just received an email with current date which I had no recollection of causing today:
![Screenshot_20200517-171614](https://user-images.githubusercontent.com/39889/82160289-47615700-9862-11ea-9971-de118f7818e8.png)

It was just an effect of the issue being moved, heh heh ;-)

**Comment by mih** [comment]
I am closing this issue. AFNI users can set `AFNI_NOREALPATH=yes`.

More generally, DataLad users that need a dataset representation without symlinks for any reason can switch particular datasets to "adjusted-unlocked" mode: https://git-annex.branchable.com/git-annex-adjust/

This is automatically done for "crippled" file systems by git annex. This command can also be executed manually in any dataset, and also recursively via `datalad foreach-dataset`, if necessary.
